"""Source-backed paraphrases, with block citations and printed examples."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
book=json.loads((ROOT/'data/grammar-book-seed/book.json').read_text(encoding='utf8'))
SPEC='''alphabet|1|125-174|Written letters and sound symbols|The book gives seven written vowels a e ɛ i o ɔ u. Its notes say c and h occur together as ch, and n and y can form ny. ŋ can begin a word. Phonetic vowel symbols describe pronunciation rather than extra ordinary written letters. The consonant list contains apparent transcription/count errors; consult the orthography guide for keyboard spelling.|alphabet,letters,consonants,vowels
vowel-harmony|1|135-142|Vowel harmony and endings|Vowel sounds fall into open and close sets. An ending must agree with the stem's vowel set: the book contrasts pa plus e giving pae, and su plus i giving sui.|vowel harmony,open vowels,close vowels,endings
length|1|143-152|Long vowels and consonants|A double vowel marks vowel length. Some noun and adjective plurals have long consonants, especially in class D. Preserve these distinctions when looking up forms.|long vowels,vowel length,long consonants
tone|1|153-168|Tone distinctions in this grammar|Tone is part of a word's pronunciation. This grammar describes low mid high and rising tones but usually leaves tone unwritten. It explicitly marks á plural you, ná if, bá will not and wó will to distinguish them from other words. This is a source-specific convention, not a general accent rule.|tone,accents,diacritics
sound-notes|1|170-194|Pronunciation and written forms|The notes discuss r between vowels, d at the beginning of simple words, and d inside words with distinct parts. They also explain that ei can represent different vowel sounds according to word position. Phonetic examples remain pronunciation evidence rather than keyboard suggestions.|pronunciation,phonetic,ei,r and d
greetings|2|197-266|Greetings and responses|Greetings depend on time of day, the number of listeners, situation, locality and preference. Exchanges can continue through several questions and responses. naa can accompany greetings wishes and exhortations. Use the printed dialogues as source examples, not universal responses.|greetings,goodbye,good night,welcome
pronoun-pronunciation|2|204-210|Pronouncing the written pronoun n|The written singular you pronoun n is commonly pronounced m before p b or m, and n before k g or n. Its realization before w can vary. The spelling remains n in the book's examples.|pronoun pronunciation,n before consonants
useful-questions|2|267-288|Questions for learning Kasem|The book supplies questions about names origin meanings and what things are called or used for, along with requests to repeat and speak carefully. These are recorded complete expressions, not templates for generating new translations.|useful questions,repeat,speak carefully
word-order|3|291-303|Subject verb and object order|The ordinary order is subject then verb then object. A clause can have no object. A small group of verbs including bere show, pa give and ke do or make can take two objects.|word order,subject verb object,two objects,SVO
adverbs|3|304-325|Adverbs time and place in clauses|Adverb time and place expressions normally follow the subject verb and object. When an adverb occurs with time or place material, the adverb comes first. The book says multiple adverb time and place phrases in one clause are unusual.|adverbs,time and place,clause order
descriptive|3|326-345|Descriptive clauses and strong forms|Descriptive verbs say what the subject is like. Some descriptive forms with n have a strong form with mm instead. The editable list has transcription damage, so use its clearly printed examples without inventing replacement forms.|descriptive clauses,descriptive verbs,strong forms
equative|3|346-357|Equative clauses with ye and dae|An equative clause relates a subject to a noun or adjective complement using ye. Its negative counterpart uses dae. This differs from describing a subject's location.|equative,copula,ye,dae
location|3|358-382|Location with wo tere wora and tera|A location clause uses wo and a place expression; its negative is tere. wora combines wo and da and means be there; tera is its negative. Depending on context, being there can also refer to being around or still alive.|location clauses,wo,tere,wora,tera
no-verb|3|383-409|Clauses without a verb|Some clauses have a subject and complement without a verb. In the examples, mo follows the subject. These are a stated exception to the usual verb-containing clause patterns.|verbless,no verb,complement
focus-order|3|410-434|Fronting and emphasis with mo|An element can move to the beginning of a clause and be followed by mo, drawing attention to that element. This often answers a question. Question elements usually come first with mo. Some short time words can also occur between subject and verb.|focus,emphasis,fronting,mo,change of order
personal-pronouns|4|448-467|Weak personal pronouns|Personal pronouns have subject and object forms. Singular subject forms are a n o; corresponding object forms are ne m o. Plural forms include dé debam, á abam and ba ba. Short object pronouns can be closely joined to a verb with a hyphen, and their tones differ from subject forms.|personal pronouns,subject pronouns,object pronouns,weak pronouns
impersonal-pronouns|4|468-479|Pronouns agree with noun class|Impersonal pronouns vary by noun class and number. The tables retain each class's forms. The editable weak-pronoun table prints dé for class B singular while the noun-class table prints de; this discrepancy is preserved instead of silently resolved.|impersonal pronouns,class pronouns,noun agreement
strong-pronouns|4|480-505|Strong pronouns|Strong or emphatic pronouns have the same form for subject and object and do not change tone in that use. Personal forms include amo nmo omo or wonto, debam abam and bamo or banto. Modifiers can follow pronouns.|strong pronouns,emphatic pronouns
determiners|4|507-544|Articles and other noun modifiers|The article follows the noun and agrees with its class and number. Demonstrative other some and certain forms also vary by class. The chart presents their order after the noun; not every modifier can occur together. This and other can sometimes precede the noun.|articles,determiners,demonstratives,noun phrases
numerals|4|546-562|Numerals and modifiers in noun phrases|Numerals two through seven and larger numerals containing them vary with noun class. One is dedoa and can agree with the noun. Numerals combine with demonstratives articles and modifiers such as all many only and also.|numerals,counting,number agreement,modifiers
relative|4|565-583|Relative clauses inside noun phrases|Relative clauses contain na and usually end in to. They may be linked to a noun by a class-agreeing who or which form such as wolo balo delo or yalo. The book also records relatives without that linker or final to.|relative clauses,who and which,relative pronouns
noun-joining|4|584-590|Joining noun phrases with de|de joins nouns or noun phrases with the meaning and. dedaane is a longer form. Clause joining uses a different construction described in chapter six.|joining nouns,noun conjunction,de
possession|4|592-607|Possession by phrase order|A possessing noun phrase or pronoun comes before the possessed noun phrase. Several noun phrases can be linked, but only the first can be a pronoun. The source illustrates nested possession.|possession,possessive,whose
adjectives|4|608-636|Adjectives and noun agreement|Adjectives follow the noun. An accompanying article agrees with the adjective's class. Many nouns use shortened forms before an adjective; the adjective changes for number. Some adjectives can stand alone, and a few require na in that position.|adjectives,adjective agreement,shortened nouns
place-time|5|643-669|Place time and ne phrases|Place and time expressions can be single words, pairs of time words, noun phrases or phrases ending in ne. A position word can precede ne, including top back bottom mouth or side forms recorded in the source.|place phrases,time phrases,locative,ne phrases
adverb-phrases|5|670-692|Adverb phrases|Adverbs can be a single word or a longer expression. The book records well much twice often and happily, among others. Some time and adverb phrases at the beginning of a sentence can end in to.|adverb phrases,often,twice
verb-phrases|5|693-701|Verb phrases contain verbs and particles|A verb phrase can include a verb and words before it that express tense or other meanings. Chapter eight explains the particles and verb classes in detail.|verb phrases,particles
chains|6|706-768|Clause chains|A clause chain repeats the first clause's subject as a weak pronoun in subsequent clauses. The first verb can show tense; following verbs usually stand without those tense words. Initial verbs can express adverbial meanings aspect ability or completion. Some adverbial constructions are exceptions.|clause chains,serial verbs,consecutive clauses
chain-tone|6|730-768|Tone in repeated chain subjects|Low-tone weak pronouns change to mid tone when repeated as subjects in ordinary clause chains; high-tone weak pronouns remain high. Chains expressing continuous action with wora are stated exceptions: their weak pronouns do not change tone.|chain tone,repeated subjects
clause-joining|6|769-787|Joining clauses with ye|ye joins clauses or clause chains. An English and does not always correspond to ye: a Kasem clause chain can express the sequence without it.|joining clauses,clause conjunction,and clauses
conditional|6|788-824|Conditional and when clauses|Conditional na follows the subject; the grammar distinguishes its tone from the na in past when clauses, which usually end in to. Conditional na can also refer to a when event that has not happened yet. The relevant verb uses a past form. These subordinate clauses precede the main clause.|conditional,if clauses,when clauses
purpose|6|825-841|Purpose clauses with se|A purpose clause starts with se and follows the main clause. It can itself be a chain. Low-tone weak subjects following se change to mid tone in the described construction.|purpose clauses,se,so that
result|6|842-850|Result clauses with pa or pa se|A result clause begins with pa or pa se and follows the main clause. It can be a clause chain. The source examples distinguish this from purpose clauses.|result clauses,pa se,consequence
sentence-building|6|851-869|Combining sentence parts|A sentence can place conditional or when material before the main clause and purpose or result material after it. Conditional clauses can be joined with ye; purpose clauses can follow one another without ye.|sentence building,subordinate clauses
sequence|6|870-878|Linking events with ma|ma follows the first subject in the main clause and signals what happened next. It is common in narratives and uses consecutive single-action forms.|narrative,sequence,ma
noun-classes|7|882-905|Five noun classes|Nouns are grouped into classes A B C D E by their singular and plural pronouns and articles. Stems combine with suffixes; the book distinguishes consonant and vowel stems and describes class-specific changes. Class is not determined only by a noun's meaning.|noun classes,noun morphology,stems,suffixes
class-a|7|907-926|Noun class A|Class A uses o and ba, and articles wom and bam. Singular endings include o or u; plural endings include a and na. Many members denote people, but some people nouns belong to other classes.|class A,people nouns
class-b|7|928-944|Noun class B|Class B uses de and ya, and dem and yam. Its typical singular suffix is e or i and plural suffix is a. Vowel-stem nouns have additional source-listed forms.|class B,noun class B
class-c|7|946-972|Noun class C|Class C uses ka and se, and kam and sem. Its singular suffix is a. Plural formation depends on stem type; the source supplies r n l stems, g and ŋ stems, and vowel stems rather than one universal replacement.|class C,noun class C
class-d|7|975-1000|Noun class D|Class D uses ko and te, and kom and tem. Singular endings include u o ɔ; plural endings and stem changes can produce long vowels or consonants. The book notes dialect variation and exceptions, including g stems.|class D,noun class D
class-e|7|1003-1016|Noun class E|Class E uses ko and de, and kom and dem. Singular endings include u o ɔ; plural endings include ne and ni, with other printed alternatives. Consult the paradigms for particular stems and dialect forms.|class E,noun class E
mixed-classes|7|1018-1032|Mixed classes and plural-only nouns|Some nouns combine a singular from one class with a plural from another. Some people nouns use class A agreement with class B endings. Some liquid nouns are recorded only in plural forms. The paradigms retain these exceptions.|mixed classes,plural only,irregular nouns
tense-aspect|8|1034-1091|Tense and kind of action|The book distinguishes past present and future, and single completed versus continuous action. Verbs belong to classes A B C D according to how their forms change. Most verbs are described as class A; particles are shared across classes.|tense,aspect,perfective,imperfective,verb classes
single-past|8|1094-1156|Past single action|Classes A and D generally use e or i; vowel stems can occur without an added ending. Classes B and C use a in the past, with changes before objects or after the negative wo. The printed paradigms list the actual forms.|past tense,past single action,did not
single-future|8|1157-1215|Future single action|Future single action uses wó, or bá for its negative, with the source's ordinary unmarked variants also present. Classes A and D retain e or i forms; classes B and C use simpler forms, often losing a past g or n. The future form does not change before an object in this description.|future tense,future single action,will not
habitual|8|1216-1279|Habitual continuous action|Continuous action can describe repeated habits or action still in progress. Habitual class A and C forms commonly use a; class B and D forms use e or i. Some a endings change before an object. The negative particle is ba. Optional negative bundles in the source must not be quoted as one exact translation.|habitual,continuous action,habitual tense
progressive|8|1280-1311|Present action in progress|Many verbs use wora with a repeated subject and continuous-action form to describe action in progress. Other posture verbs can serve similarly. Motion verbs use maa instead; coming has different habitual and in-progress forms in the book.|progressive,present continuous,action in progress,maa
future-continuous|8|1312-1366|Future continuous action|Future particles combine with ta: wó ta for positive and bá ta for negative. Verb forms follow the continuous-action pattern, with relevant changes before an object. This section occurs twice in the editable source; the clearer duplicate supports the quoted examples.|future continuous,future progressive,ta
past-continuous|8|1368-1374|Past continuous action|Past continuous or habitual action uses the continuous forms with time words or particles such as ya or déem to locate the action in the past. The source also records an earlier ongoing interpretation.|past continuous,past habitual,used to
consecutive|8|1377-1411|Consecutive single action|Consecutive forms express actions following one another. They use future single-action forms without future particles, including later links of clause chains and constructions after ma se pa or ye. Their endings do not change in the stated pattern.|consecutive tense,consecutive verbs
commands|8|1412-1462|Commands and prohibitions|Single-action and continuous commands differ. Continuous commands use ta and can include n or the plural pronoun. Negative commands use yé; plural commands often add na. Most single-action commands use the simple or future form, with class C exceptions and explicitly listed irregular forms.|commands,imperative,prohibitions,negative commands
particle-summary|8|1463-1474|Particle and verb-form summaries|The verb table organizes continuous past future and command forms by class, showing different pre-object forms in parentheses. The particle summary in the editable copy is damaged and is not used to manufacture missing cells. Clear prose and the complete verb table remain available.|verb forms,verb table,particle summary
small-words|9|1480-1549|Small words before verbs|The book distinguishes ma for the next single event and maa for additional facts or motion in progress. It also discusses laam daa nam ya deem and doom for sequence repetition contrast and time. Their tone and context matter; they are not interchangeable English words.|small words,preverbal particles,remote past,doom,deem
attention|9|1550-1564|Commands attention and focus particles|na can follow plural commands; naa holds attention in greetings and instructions; mo draws attention to new information. These uses differ from conditional and question uses of similar written forms.|attention particles,naa,focus particles,plural commands
yes-no|9|1566-1579|Yes or no questions|na can occur at the end of a yes or no question, often after mo. It can be omitted with lengthening and falling intonation. Printed question punctuation does not replace the pronunciation evidence.|yes or no questions,question particle,polar questions
information-questions|9|1581-1633|Asking for information|The source lists where what who whose which when how many how and why expressions. Some question words or forms agree with noun class or number. Quote the complete printed questions; do not compose a new question from isolated entries.|question words,information questions,where,why,how many'''
rules=[]
for line in SPEC.splitlines():
    key,ch,span,title,summary,triggers=line.split('|');lo,hi=map(int,span.split('-'))
    examples=[e for e in book['examples'] if not e.get('ambiguous') and lo<=int(e['sourceRef'].rsplit(' ',1)[1])<=hi][:3]
    rules.append({'key':key,'topic':key,'chapter':int(ch),'pages':f'Chapter {ch}, DOCX blocks {span}','title':title,'summary':summary,'triggers':triggers.split(','),'examples':[[e['kasem'],e['english']] for e in examples],'sourceRefs':[f'Chapter {ch}, DOCX blocks {span}'],'attribution':book['attribution'],'note':'Source-backed paraphrase. Consult the chapter reference for the printed tables, examples and transcription limitations.'})
(ROOT/'data/grammar-book-seed/rules.json').write_text(json.dumps(rules,ensure_ascii=False,indent=2)+'\n',encoding='utf8')
print(f'Prepared {len(rules)} rules covering all nine chapters.')
