import type { ReactNode } from "react";
import { Link } from "../app/router";

export interface PrivacySection { id: string; title: string; shortTitle: string; content: ReactNode; }

/** Reviewed against implementation on 2026-10-02; docs/product/privacy-notice-evidence.md. */
export const PRIVACY_SECTIONS: PrivacySection[] = [
  { id: "scope", title: "Who this notice covers", shortTitle: "The ecosystem", content: <>
    <p>Indigen World connects language learning, cultural creation and community stewardship. This notice covers the public website and Kasem dictionary, the Indigen World mobile app (Indigen), TribeStudio and its contributor workspace, and Indigen World Labs. It also explains how the internal Admin console supports these services. Project Kassena is our flagship Kasem-language programme; Venacula is our newsletter.</p>
    <p>Information can move between products when you choose a connected action. A contribution made in TribeStudio may be reviewed in Admin and, when approved for publication, appear in the dictionary or mobile app. Signing in does not make all your work public. Below we distinguish local information, private account records and published material.</p>
    <p>This notice describes implemented workflows. Features, advertising, memberships and experimental tools may be available only in particular builds, regions or account roles. Inclusion here does not mean a feature is enabled for everyone. External services linked from our products have their own privacy notices.</p>
  </> },
  { id: "website", title: "The website, dictionary and updates", shortTitle: "Website & dictionary", content: <>
    <p>The Pause animations choice is saved in this browser so it carries across pages and visits. It is not sent to our servers. Your device’s reduced-motion setting is also respected automatically. Clearing this site’s browser storage resets the saved choice.</p>
    <p>You can browse public pages and published dictionary entries without a contributor account. Opening a page, image, recording or video sends an ordinary network request to its host. Hosting services can process technical information such as an IP address, browser information and request time to deliver the resource and maintain security.</p>
    <p>The public website’s saved dictionary words are stored in your browser on that device. Saving a word there does not create a cloud backup or a shared profile. You can unsave words or clear this site’s browser storage; clearing storage can also remove preferences and sign-in state.</p>
    <p>Updates are hosted on Blogger. The website loads a public summary feed to show recent articles, and article links open the updates site. Blogger and other destinations you open may use their own cookies and technical logs. Public content, including an approved entry and its published attribution, can be read, linked to or copied by other visitors.</p>
  </> },
  { id: "forms", title: "Contact, involvement and tester forms", shortTitle: "Forms & requests", content: <>
    <p>We collect the fields you submit. Contact forms include a name, email address, subject and message. Get Involved forms can include contact details, country, organisation, your participation route and a note. Tester recognition forms collect the participation and delivery details shown on that form.</p>
    <p>These records help us answer questions, route requests, verify tester participation and administer the recognition described on the form. Submissions are stored for the team. Contact or involvement details may also be included in a team email alert. Acknowledgements and operational replies are sent through our email service.</p>
    <p>To limit spam, the form service derives a hashed identifier from the request’s IP address and uses it for rate limiting, separately from your message. General forms are not the route for recordings, children’s personal information, sacred or restricted knowledge, or detailed cultural submissions. Use the relevant contribution workflow, or contact us first about an appropriate process.</p>
  </> },
  { id: "newsletter", title: "Venacula and service messages", shortTitle: "Newsletter & messages", content: <>
    <p>Venacula subscription records include your email, optional country, subscription status and the version and time of your consent. Signing in, contributing or contacting us does not subscribe you to the newsletter.</p>
    <p>A new subscription can receive a welcome acknowledgement. Regular newsletter delivery is being prepared and must include a working unsubscribe link before it begins. Until that link is available, use the <Link to="contact">contact page</Link> to request removal. We do not sell form or subscriber information or publish those responses.</p>
    <p>Account invitations, assignment notices, review decisions, support replies and payment updates are operational messages. Depending on the workflow and contact details supplied, they can be delivered in the product, by email, SMS or push notification. Delivery services receive the destination and message needed to send it. Push delivery uses a device registration token associated with the account. Newsletter opt-out is separate from messages needed to administer an account or request.</p>
  </> },
  { id: "accounts", title: "Accounts, profiles and access", shortTitle: "Accounts & access", content: <>
    <p>Firebase Authentication handles sign-in for connected products. We process an account identifier and the profile or sign-in information you provide, such as an email and display name. If you choose a supported external sign-in method, that provider participates in authentication. Session information lets you remain signed in.</p>
    <p>Roles and access claims determine which contributor, creator, validator, finance or administrative features you can use. Invited contributors may also have a contact phone number, invitation delivery status and assigned work. Operational contact details and payment records are separate from published attribution.</p>
    <p>Where a profile or post displays your name, avatar or creator identity, other users of that surface can see it. Check public fields before publishing. Keep credentials private, sign out on shared devices, and contact us if an invitation, role or account appears incorrect.</p>
  </> },
  { id: "mobile", title: "The mobile app and offline information", shortTitle: "Mobile & offline use", content: <>
    <p>Indigen supports offline use. Saved words, contribution and correction drafts, downloaded resources and queued submissions can remain on your phone. Local drafts stay there until you choose a submission or synchronisation action. A queued submission is an instruction to send that work when the queue is processed; it differs from an unsubmitted draft.</p>
    <p>Signing in, submitting a correction or contribution, or using a connected feature sends the information needed for that action to our backend. This can include account identity, selected content, media and review metadata. An offline copy can continue to exist after a server-side change, until it is refreshed or removed.</p>
    <p>Use available saved-item and draft controls to remove local work. Device storage settings can remove additional local data and downloads. Uninstalling or clearing app data does not by itself delete contributions, messages or account records already sent to the service.</p>
  </> },
  { id: "community", title: "Community, Explore and conversations", shortTitle: "Community & sharing", content: <>
    <p>Posts, attached media, replies, reactions, likes, comments and saves are processed with the account and content identifiers needed to operate Community and Explore. Published posts and attributed Explore material are visible to the audience of that surface. A private community’s membership controls govern access within the service; they cannot prevent an authorised participant from copying what they can see.</p>
    <p>Connected conversations store message content and sender, recipient or conversation information needed for delivery. Notifications may include a message preview. Do not assume conversations are end-to-end encrypted: this notice makes no such claim. Reports and moderation workflows can make relevant content available to authorised reviewers.</p>
    <p>Sharing a public post or community link outside the app can expose its available preview to the person opening it. Consider names, faces, locations and permissions before posting someone else’s material. A save, public reply and private draft have different audiences.</p>
  </> },
  { id: "studio", title: "TribeStudio and contributor work", shortTitle: "TribeStudio & contributors", content: <>
    <p>Depending on the task, submissions can include words and meanings, expressions, translations, dialect and tone notes, corrections, stories, proverbs, oral histories, sources, uncertainty flags, recordings and other media. Consent, licence, attribution and cultural-permission fields describe how the material may be handled.</p>
    <p>Contributor workspaces retain assignments, saved responses, submission times, progress and reviewer feedback. Review decisions, notes, revision requests, publication links and audit records support accountable governance. Submitted work is available to authorised people who assess it; it is not automatically a public dictionary entry.</p>
    <p>Points, streaks, campaigns, bounty participation and redemption history are associated with your account to operate the relevant programme. Review and payment states are recorded separately. Pending work or points do not guarantee approval or payment. Availability and reward conditions are described in the relevant workspace.</p>
  </> },
  { id: "payments", title: "Memberships, rewards and payment details", shortTitle: "Payments & rewards", content: <>
    <p>Contributor payment profiles contain the details needed for the selected method: for example, bank name, account holder, account number and branch, or mobile-money number and network. Where requested, supporting statements or documents help check the profile. Payment requests retain the amount, method, review decision, reference and payment state.</p>
    <p>These are operational and financial records for authorised staff, not public profile fields. Only provide documents requested in the payment workflow. Keep unrelated transactions and other people’s information out of supporting documents wherever possible.</p>
    <p>A deployment can enable an automated statement comparison using Google’s AI service. When enabled, the uploaded document and supplied account number are sent for comparison; a human finance reviewer makes the verification decision. This check is disabled by default and is separate from general creative AI tools. Provider logging and retention depend on the configured service, so an uploaded statement should not be treated as staying only on your device.</p>
    <p>Membership or advertising purchases may use Google Play billing or Paystack, depending on the product and checkout. The provider handles checkout information and its own fraud and transaction records. Indigen World processes references, verification results and entitlement or campaign status to recognise the purchase. Providers have their own privacy terms; do not send card details through general contact forms.</p>
  </> },
  { id: "labs", title: "Indigen World Labs", shortTitle: "Labs & experiments", content: <>
    <p>Labs is an experimental space for language practice, Culture Quest contribution missions and cultural story creation. Signed-in practice records can include selected sources, answers, results and session activity. Story drafts can include a title, format, source references, your context, text and revisions. Feedback and language-concern reports retain the information you supply and the relevant experiment or source.</p>
    <p>Culture Quest associates a daily set of source cards, completed missions and cumulative XP and mission counts with your account. A submitted usage note or correction includes your description and supporting context or evidence, linked to the selected source, for the feedback review process. Quest completion and XP do not by themselves publish the note or guarantee a contributor payment.</p>
    <p>Saved story drafts are account-private within application access controls. Saving them does not make them public archive material. You can reopen or delete your own saved drafts using the available controls. Authorised reviewers receive reports and can respond; internal notes are separate from the response shown to the reporter.</p>
    <p>Experiments can be paused, limited to signed-in users, or have AI assistance disabled. A guided template can work without an AI call. If story assistance is enabled and you request it, your context and selected English source meanings and context are sent to the configured Google service. Creative output is labelled unverified and requires review.</p>
  </> },
  { id: "ai", title: "Kawuri, AI assistance and generated media", shortTitle: "AI & generated media", content: <>
    <p>Features such as Kawuri, contributor assistance and Studio media generation process the prompt, context and reference material required for your chosen action. That material can be sent to the configured model provider. Studio integrates Google Gemini, including Gemini Omni video, and, for supported workflows, Runway and fal. Availability depends on configuration and access.</p>
    <p>Generation records can include prompts, model, provider, job identifiers, timestamps, outcomes, usage information and generated files. Studio’s generated video is saved in private storage for the relevant workflow; publishing or sharing is a separate action. Exports and downloads create copies outside the service’s control.</p>
    <p>Do not include confidential account information, payment documents, another person’s personal details or restricted cultural material in a prompt unless the workflow and permissions allow that processing. Provider retention and use rules vary by service and configuration; we do not promise every provider deletes inputs immediately. AI output does not establish consent, ownership, cultural authority or a verified translation. Review it before use.</p>
  </> },
  { id: "advertising", title: "Advertising and your privacy choices", shortTitle: "Advertising choices", content: <>
    <p>Guests and free members may see advertising in Community, Explore and Collection. Suitable campaigns placed directly with Indigen World take priority. When no suitable direct campaign is available, Google Mobile Ads (AdMob) can fill the position after the required privacy flow. Paid Indigen Plus, Patron and Creator entitlements remove both kinds of advertising where the membership is supported.</p>
    <p>Google ads may involve an advertising identifier, device and app information, approximate region and advert interactions for delivery, measurement and fraud prevention, and personalisation where your choices permit it. We do not send keyboard text, payment documents or cultural contribution text as advert content. First-party campaign interactions and performance records also support delivery and reporting.</p>
    <p>Where required, Google’s consent message is presented and an <strong>Advertising privacy choices</strong> entry is available in Settings. Use it to revisit your choices. If an ad request is not permitted or no advert is returned, the position is removed. An implemented integration does not guarantee production adverts are serving. Read <a href="https://policies.google.com/technologies/ads">Google’s advertising information</a> for its practices.</p>
  </> },
  { id: "keyboard", title: "The optional Kasem keyboard", shortTitle: "Kasem keyboard", content: <>
    <p>The Android app includes a Kasem system keyboard that you enable and select in Android’s keyboard settings. It is never enabled for you. It can be used in Indigen, messaging apps, browsers and other places where Android lets you type.</p>
    <p><strong>The keyboard does not collect or transmit what you type.</strong> It has no learning dictionary, predictions, typing history or analytics. Characters go to the active app’s input connection. The keyboard does not store them, send them to Indigen World’s backend, or pass them to the rest of Indigen. It works without a network connection.</p>
    <p>It saves only local preferences: starting language, key vibration and key sounds. The app you type into receives the text and handles it under its own privacy practices; the keyboard cannot control that destination app. You can switch keyboards or disable Kasem in Android’s settings at any time.</p>
  </> },
  { id: "media", title: "Microphone, media and background playback", shortTitle: "Recordings & playback", content: <>
    <p>The app requests microphone permission when you choose a recording feature, such as a pronunciation or audio contribution. Recording begins when you start it and ends when you stop it. A local recording is not uploaded merely because permission was granted; submission sends it with the contribution and associated metadata.</p>
    <p>If you select a photo, video or audio file for a post or creation task, the chosen file is processed by that workflow. Media can contain visible faces, spoken names or embedded metadata you did not intend to share. Review the file and ensure the people represented and material’s custodians have agreed to the intended use.</p>
    <p>Music playback can continue while Indigen is in the background or the screen is off, with a media notification providing controls while audio plays. The background playback service supports that playback; it does not use the microphone to listen to your surroundings. Stop playback or manage microphone and notification permissions in device settings.</p>
  </> },
  { id: "culture", title: "Cultural permissions, attribution and publication", shortTitle: "Cultural permissions", content: <>
    <p>Cultural information can carry responsibilities beyond individual privacy. Consent, licensing, source, attribution, dialect and cultural-permission records stay associated with material so reviewers can assess whether and how it may be used. Submission is not permission for every future purpose.</p>
    <p>Publication is subject to the applicable workflow and permissions. Published records may include an approved meaning, recording, source or contributor attribution. Restricted and sacred material requires a dedicated, consent-based process; never place it in an ordinary form, public post or general AI prompt. Ask the team about appropriate handling before submission.</p>
    <p>Request a correction, attribution change, restriction review or takedown through the <Link to="contact">contact page</Link>, giving the record or link and concern. We may need to check authority, permissions and provenance before changing a record. Removing a publication cannot recall copies others have already downloaded or shared.</p>
  </> },
  { id: "operations", title: "Support, moderation and internal administration", shortTitle: "Support & governance", content: <>
    <p>Support and issue reports can include a category, message, assignment or content reference, and the reporting account. Status and replies are stored so you can follow the outcome. Do not include passwords, full card details or unrelated private documents in support messages.</p>
    <p>Admin is an internal console, not a public product. Authorised staff use it for access management, assignments, cultural review, publication, campaigns, support and finance. Different responsibilities have different access requirements. Internal notes, payment details and unpublished submissions are not intended for public browsing.</p>
    <p>Audit records identify relevant actions, actors, times and decisions so changes can be investigated. Technical logs, rate limits, app-integrity checks and error reports help operate services and detect abuse. These records differ from public profile information and may need to remain available while a support or governance matter is being resolved.</p>
  </> },
  { id: "analytics", title: "Analytics, diagnostics and device storage", shortTitle: "Analytics & storage", content: <>
    <p>The website’s optional Firebase Analytics integration requires the relevant build configuration. Its event vocabulary covers page views, CTA choices, feature navigation and form outcomes. Our event properties are designed to exclude messages, names, email addresses, phone numbers and cultural submission content. This does not mean the provider processes no technical device or network information.</p>
    <p>Where enabled in production, mobile analytics, crash reporting and performance diagnostics can process usage events, app version, device or operating-system information, error traces and technical identifiers. Production telemetry is disabled outside production builds. Diagnostics help understand failures and improve reliability; they are different from recording conversations or keyboard input.</p>
    <p>Browser or device storage supports authentication sessions, preferences, saved resources and drafts. Optional analytics and third-party pages can involve cookies or similar identifiers. You can clear site storage and manage device permissions. Clearing local storage does not erase information already held on the server.</p>
  </> },
  { id: "providers", title: "Service providers and processing locations", shortTitle: "Service providers", content: <>
    <p>Google/Firebase supports hosting, authentication, databases, file storage and backend services. Configured workflows also use our email delivery service, Arkesel for SMS, Firebase Cloud Messaging for push notifications, payment processing, advertising and AI providers. Data sent depends on the action: an SMS service needs a destination and message; a video model needs the prompt and reference material.</p>
    <p>Providers may process information outside your country. Do not assume every product, database, log, backup or AI endpoint is hosted in Ghana or one region. Access controls and configuration govern our use; provider terms govern their own responsibilities.</p>
    <p>Read <a href="https://firebase.google.com/support/privacy">Firebase privacy and security</a>, <a href="https://policies.google.com/privacy">Google’s privacy policy</a>, <a href="https://paystack.com/privacy">Paystack’s privacy policy</a>, <a href="https://runwayml.com/privacy-policy">Runway’s privacy policy</a> and <a href="https://fal.ai/privacy">fal’s privacy policy</a>. A provider link describes that service; it does not mean every visitor’s information goes to every provider.</p>
  </> },
  { id: "retention", title: "Retention, security and removal limits", shortTitle: "Retention & security", content: <>
    <p>Local information remains until you remove it or the product or device clears it. Server records support account operation, review, support, consent evidence, reward administration and payment reconciliation. Retention differs by record type. We do not currently publish a single fixed deletion period for the entire ecosystem.</p>
    <p>Authentication, role checks, database and storage rules, and restricted backend actions help protect access. No service can promise perfect security. Shared devices, downloaded exports, public posts and third-party copies require care beyond our access controls.</p>
    <p>Deletion can require separate action for an account, private draft, uploaded file and public record. Audit, payment, consent or dispute records may require review before removal; provider logs or backups can have separate retention. We will explain relevant limits when handling a request rather than promise immediate deletion of every copy.</p>
  </> },
  { id: "rights", title: "Your choices and privacy requests", shortTitle: "Your choices & requests", content: <>
    <p>Request access to information associated with you, a correction, deletion, withdrawal of recorded consent, or review of attribution or publication through the <Link to="contact">contact page</Link>. State which product you used, the account email or public link, and what you want changed. Do not send a password or identity document in the first message.</p>
    <p>We may need to verify you control the account or are authorised to act for a person or cultural record. Account and server-side requests are handled manually by the team during this stage. We will explain records that must be retained, effects on connected work and any further information needed. Available legal rights can depend on where you live.</p>
    <p>You can also unsave local words, remove drafts where controls exist, delete your own Labs story drafts, change device permissions, revisit advertising choices and stop newsletter participation. Signing out closes a session; it does not remove server records.</p>
  </> },
  { id: "children-changes", title: "Children’s information and changes to this notice", shortTitle: "Children & policy changes", content: <>
    <p>General forms are not designed to collect children’s personal information. School or youth partnerships need an agreed process covering responsible adults, permissions, intended audience and appropriate handling. Do not upload a child’s recording, image or identifying details through an ordinary contribution, public post or AI-generation workflow.</p>
    <p>If you believe a child’s information or cultural material was submitted without required authority, contact us with the relevant link or product so the team can review it. Avoid repeating sensitive material in the initial message.</p>
    <p>We will update this page as workflows and providers change and show the review date above. A new feature may have its own notice or permission step. This remains a plain-language implementation notice pending final legal approval; that status does not replace the choices and request routes described here.</p>
  </> },
];
