import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:indigen_world_mobile/core/brand.dart';
import 'package:indigen_world_mobile/domain/dictionary_entry.dart';
import 'package:indigen_world_mobile/features/community/data/community_space_providers.dart';
import 'package:indigen_world_mobile/features/dictionary/entry_detail_screen.dart'
    show PronunciationButton;
import 'package:indigen_world_mobile/features/dictionary/word_lookup.dart';
import 'package:indigen_world_mobile/features/explore/reel_view.dart';
import 'package:indigen_world_mobile/features/kawuri/kawuri_models.dart';
import 'package:indigen_world_mobile/features/kawuri/kawuri_service.dart';
import 'package:indigen_world_mobile/shared/glass_popup.dart';
import 'package:indigen_world_mobile/shared/night_theme.dart';

// ── Words the dictionary knows ──────────────────────────────────────────────

/// One word from a caption with its published dictionary senses.
class ReelWordMatch {
  const ReelWordMatch({required this.word, required this.senses});

  /// The word as it was written in the caption.
  final String word;
  final List<DictionaryEntry> senses;
}

/// Words in [text] the published dictionary knows, in reading order, once
/// each, at most [limit] of them.
///
/// The same index the Community feed uses to make words tappable — see
/// `dictionaryIndexProvider` — so a word that teaches in a post teaches in a
/// reel too, and the two can never disagree about what it means.
List<ReelWordMatch> reelWordMatches(
  String text,
  Map<String, List<DictionaryEntry>> index, {
  int limit = 12,
}) {
  if (text.trim().isEmpty || index.isEmpty) return const [];
  final seen = <String>{};
  final matches = <ReelWordMatch>[];
  for (final match in wordPattern.allMatches(text)) {
    final written = match.group(0) ?? '';
    final key = normaliseWord(written);
    if (key.length < 2 || !seen.add(key)) continue;
    final senses = index[key];
    if (senses == null || senses.isEmpty) continue;
    matches.add(ReelWordMatch(word: written, senses: senses));
    if (matches.length >= limit) break;
  }
  return matches;
}

/// The text of a reel worth reading for words: its title and its caption.
String reelReadableText(Reel reel) => [
  reel.title,
  if (reel.caption.trim() != reel.title.trim()) reel.caption,
].where((part) => part.trim().isNotEmpty).join('\n');

/// Whether [reel] has anything a translation panel could show.
bool reelHasTranslation(Reel reel, Map<String, List<DictionaryEntry>> index) =>
    !reel.isSponsored &&
    (reel.englishSummary.trim().isNotEmpty ||
        reel.translations.isNotEmpty ||
        reelWordMatches(reelReadableText(reel), index, limit: 1).isNotEmpty);

// ── Where a piece of information came from ──────────────────────────────────

/// The four kinds of source the Context sheet speaks from, kept visually
/// distinct so a member can always tell a creator's own words from a reviewed
/// fact from a machine's guess.
enum ReelContextSource {
  /// Written by whoever published the piece.
  creator('Creator-provided', Icons.person_outline_rounded),

  /// Approved by a person on the Indigen World review desk.
  reviewed(
    'Reviewed by the Indigen World review desk',
    Icons.verified_outlined,
  ),

  /// From the published dictionary, which the community compiles and reviews.
  dictionary('Community-reviewed dictionary', Icons.menu_book_outlined),

  /// Generated by Kawuri. Never presented as fact.
  ai('AI-generated · not verified', Icons.auto_awesome_outlined);

  const ReelContextSource(this.label, this.icon);

  final String label;
  final IconData icon;
}

class ReelSourceTag extends StatelessWidget {
  const ReelSourceTag({required this.source, super.key});

  final ReelContextSource source;

  @override
  Widget build(BuildContext context) {
    final brand = context.brand;
    final colour = switch (source) {
      ReelContextSource.creator => brand.mutedInk,
      ReelContextSource.reviewed => brand.success,
      ReelContextSource.dictionary => brand.accent,
      ReelContextSource.ai => brand.gold,
    };
    return Semantics(
      label: 'Source: ${source.label}',
      excludeSemantics: true,
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(999),
          border: Border.all(color: colour.withValues(alpha: 0.6)),
          color: colour.withValues(alpha: 0.1),
        ),
        child: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(source.icon, size: 12, color: colour),
            const SizedBox(width: 4),
            Flexible(
              child: Text(
                source.label,
                style: TextStyle(
                  color: colour,
                  fontSize: 11,
                  fontWeight: FontWeight.w700,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ── The Context sheet ───────────────────────────────────────────────────────

/// The three resting heights of the Context sheet: a glance, half the screen,
/// and nearly all of it.
const double kContextCollapsed = 0.28;
const double kContextMedium = 0.55;
const double kContextExpanded = 0.94;

/// Past this, the sheet covers enough of the reel that it pauses.
const double kContextPauseExtent = 0.7;

/// Opens the Context sheet over the reel.
///
/// A modal route over the feed rather than a navigation away from it, so the
/// member's place — the reel, and where they were in it — is exactly where
/// they left it when the sheet closes. [onExtentChanged] reports the sheet's
/// height as it is dragged, which is how the feed knows to pause once the
/// sheet is covering most of the frame.
Future<void> showReelContextSheet(
  BuildContext context, {
  required Reel reel,
  required String creatorName,
  required String handle,
  required VoidCallback onOpenCreator,
  VoidCallback? onOpenCommunity,
  VoidCallback? onPronunciationPlay,
  VoidCallback? onTranslationOpen,
  ValueChanged<double>? onExtentChanged,
  bool startExpanded = false,
}) => showModalBottomSheet<void>(
  context: context,
  isScrollControlled: true,
  useSafeArea: true,
  backgroundColor: Colors.transparent,
  barrierColor: Colors.black26,
  // The sheet draws its own handle on its own surface; the theme's would float
  // above it over the video.
  showDragHandle: false,
  builder: (sheetContext) => NightTheme(
    child: NotificationListener<DraggableScrollableNotification>(
      onNotification: (notification) {
        onExtentChanged?.call(notification.extent);
        return false;
      },
      child: DraggableScrollableSheet(
        expand: false,
        initialChildSize: startExpanded ? kContextExpanded : kContextMedium,
        minChildSize: kContextCollapsed,
        maxChildSize: kContextExpanded,
        snap: true,
        snapSizes: const [kContextMedium],
        builder: (context, scrollController) => ReelContextBody(
          reel: reel,
          creatorName: creatorName,
          handle: handle,
          scrollController: scrollController,
          onOpenCreator: () {
            Navigator.of(sheetContext).pop();
            onOpenCreator();
          },
          onOpenCommunity: onOpenCommunity == null
              ? null
              : () {
                  Navigator.of(sheetContext).pop();
                  onOpenCommunity();
                },
          onPronunciationPlay: onPronunciationPlay,
          onTranslationOpen: onTranslationOpen,
        ),
      ),
    ),
  ),
);

class ReelContextBody extends ConsumerWidget {
  const ReelContextBody({
    required this.reel,
    required this.creatorName,
    required this.handle,
    required this.onOpenCreator,
    this.scrollController,
    this.onOpenCommunity,
    this.onPronunciationPlay,
    this.onTranslationOpen,
    super.key,
  });

  final Reel reel;
  final String creatorName;
  final String handle;
  final ScrollController? scrollController;
  final VoidCallback onOpenCreator;
  final VoidCallback? onOpenCommunity;
  final VoidCallback? onPronunciationPlay;
  final VoidCallback? onTranslationOpen;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final brand = context.brand;
    final index = ref.watch(dictionaryIndexProvider);
    final words = reelWordMatches(reelReadableText(reel), index);
    final space = reel.community == null
        ? null
        : ref.watch(communitySpaceProvider(reel.community!.id)).asData?.value;
    final creatorSource = reel.isReviewed
        ? ReelContextSource.reviewed
        : ReelContextSource.creator;
    final hasMeaning =
        reel.englishSummary.trim().isNotEmpty || reel.translations.isNotEmpty;
    final hasCulture = reel.culturalNotes.trim().isNotEmpty;
    final hasAnyContext = hasMeaning || hasCulture || words.isNotEmpty;

    return DecoratedBox(
      decoration: BoxDecoration(
        color: brand.surfaceElevated,
        borderRadius: const BorderRadius.vertical(top: Radius.circular(24)),
        border: Border(top: BorderSide(color: brand.border)),
      ),
      child: ListView(
        controller: scrollController,
        padding: const EdgeInsets.fromLTRB(20, 0, 20, 32),
        children: [
          const _SheetHandle(),
          Text(
            [
              reel.categoryLabel,
              if (reel.languageLabel.isNotEmpty)
                reel.languageLabel.toUpperCase(),
            ].join(' · '),
            style: TextStyle(
              color: brand.gold,
              fontSize: 11,
              fontWeight: FontWeight.w800,
              letterSpacing: 1.1,
            ),
          ),
          // A published piece has a title of its own. A community post has
          // only what its author wrote, which is read as words, not set as a
          // headline.
          if (reel.title.trim().isNotEmpty &&
              reel.title.trim() != reel.caption.trim()) ...[
            const SizedBox(height: 6),
            Text(
              reel.title.trim(),
              style: TextStyle(
                color: brand.ink,
                fontSize: 20,
                height: 1.25,
                fontWeight: FontWeight.w800,
              ),
            ),
          ],
          const SizedBox(height: 4),
          Text(
            handle.isEmpty ? 'By $creatorName' : 'By $creatorName · @$handle',
            style: TextStyle(color: brand.mutedInk, fontSize: 13.5),
          ),
          if (reel.caption.trim().isNotEmpty) ...[
            const SizedBox(height: 10),
            _Body(reel.caption.trim()),
          ],
          const SizedBox(height: 12),
          Wrap(
            spacing: 6,
            runSpacing: 6,
            children: [
              _Fact(icon: Icons.source_outlined, text: reel.sourceLabel),
              if (reel.languageLabel.isNotEmpty)
                _Fact(icon: Icons.translate_rounded, text: reel.languageLabel),
              if (reel.dialect.trim().isNotEmpty)
                _Fact(
                  icon: Icons.record_voice_over_outlined,
                  text: reel.dialect.trim(),
                ),
              if (reel.community case final community?)
                _Fact(
                  icon: Icons.diversity_3_rounded,
                  text: space?.name ?? community.name,
                ),
              if (space != null && space.location.trim().isNotEmpty)
                _Fact(icon: Icons.place_outlined, text: space.location.trim()),
            ],
          ),
          if (reel.ageRating == '13+') ...[
            const SizedBox(height: 16),
            const _Notice(
              icon: Icons.info_outline_rounded,
              title: 'Content note',
              body:
                  'The creator declared that this piece involves minors. '
                  'Please share it with care.',
            ),
          ],
          if (!hasAnyContext) ...[
            const SizedBox(height: 16),
            const _Notice(
              icon: Icons.menu_book_outlined,
              title: 'No context has been added yet',
              body:
                  'The creator has not written a translation or cultural '
                  'notes for this piece, and none of its words are in the '
                  'dictionary yet. Its attribution is below.',
            ),
          ],
          if (hasMeaning) ...[
            _Section(
              title: 'Meaning and translation',
              source: creatorSource,
              children: [
                if (reel.englishSummary.trim().isNotEmpty)
                  _Body(reel.englishSummary.trim()),
                if (reel.translations.isNotEmpty) ...[
                  if (reel.englishSummary.trim().isNotEmpty)
                    const SizedBox(height: 8),
                  for (final meaning in reel.translations) _Bullet(meaning),
                ],
              ],
            ),
          ],
          if (words.isNotEmpty)
            _Section(
              title: 'Words in this post',
              source: ReelContextSource.dictionary,
              children: [
                for (final match in words)
                  ReelWordRow(
                    match: match,
                    onPronunciationPlay: onPronunciationPlay,
                    onOpened: onTranslationOpen,
                  ),
              ],
            ),
          if (hasCulture)
            _Section(
              title: 'Cultural context',
              source: creatorSource,
              children: [_Body(reel.culturalNotes.trim())],
            ),
          if (!reel.isSponsored)
            _Section(
              title: 'Explanation',
              source: ReelContextSource.ai,
              children: [ReelAiExplanation(reel: reel)],
            ),
          _Section(
            title: 'Source and attribution',
            children: [
              ReelAttributionDetails(
                reel: reel,
                creatorName: creatorName,
                handle: handle,
              ),
            ],
          ),
          if (!reel.isSponsored)
            _Section(
              title: 'Related',
              children: [
                _RelatedLink(
                  icon: Icons.person_outline_rounded,
                  label: 'More from $creatorName',
                  onTap: onOpenCreator,
                ),
                if (onOpenCommunity != null && reel.community != null)
                  _RelatedLink(
                    icon: Icons.diversity_3_rounded,
                    label: 'Posts in ${space?.name ?? reel.community!.name}',
                    onTap: onOpenCommunity!,
                  ),
              ],
            ),
        ],
      ),
    );
  }
}

/// Who made it, where it came from, and on what terms it is shown — the
/// provenance every Explore item carries, laid out as a list of facts.
class ReelAttributionDetails extends StatelessWidget {
  const ReelAttributionDetails({
    required this.reel,
    required this.creatorName,
    required this.handle,
    super.key,
  });

  final Reel reel;
  final String creatorName;
  final String handle;

  @override
  Widget build(BuildContext context) {
    final brand = context.brand;
    final rows = <(String, String)>[
      if (!reel.isSponsored)
        ('Creator', handle.isEmpty ? creatorName : '$creatorName (@$handle)'),
      ('Source', reel.sourceLabel),
      if (reel.sourceAttribution.trim().isNotEmpty)
        ("Creator's stated source", reel.sourceAttribution.trim()),
      if (reel.community case final community?) ('Community', community.name),
      ('Category', _sentenceCase(reel.categoryLabel)),
      if (reel.languageLabel.isNotEmpty) ('Language', reel.languageLabel),
      if (reel.createdAt case final created?)
        ('Created', formatReelDate(created)),
      if (reel.publishedAt case final published?)
        ('Published', formatReelDate(published)),
      if (reel.isLive && !reel.isCommunity && !reel.isSponsored)
        (
          'Review',
          reel.isReviewed
              ? 'Approved on the Indigen World review desk'
              : 'Published by the creator without review',
        ),
      ('Permission', reel.credit),
    ];
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        for (final (label, value) in rows)
          Padding(
            padding: const EdgeInsets.only(bottom: 9),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                SizedBox(
                  width: 118,
                  child: Text(
                    label,
                    style: TextStyle(
                      color: brand.mutedInk,
                      fontSize: 12.5,
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
                Expanded(
                  child: Text(
                    value,
                    style: TextStyle(
                      color: brand.ink,
                      fontSize: 13.5,
                      height: 1.35,
                    ),
                  ),
                ),
              ],
            ),
          ),
      ],
    );
  }
}

/// Opens the attribution on its own, from the overflow menu.
Future<void> showReelAttribution(
  BuildContext context, {
  required Reel reel,
  required String creatorName,
  required String handle,
}) => showGlassPopup<void>(
  context: context,
  title: 'Attribution',
  subtitle: reel.title.trim().isEmpty ? null : reel.title.trim(),
  builder: (popupContext) => ReelAttributionDetails(
    reel: reel,
    creatorName: creatorName,
    handle: handle,
  ),
);

// ── The translation panel ───────────────────────────────────────────────────

/// Opens the translation panel: the words as written, what they mean, and the
/// words the dictionary can say aloud.
///
/// Smaller than the Context sheet and about one thing. It never pretends to be
/// a translation of the whole caption unless the creator wrote one — word by
/// word glosses are labelled as the dictionary's, and nothing is machine
/// translated here.
Future<void> showReelTranslationSheet(
  BuildContext context, {
  required Reel reel,
  VoidCallback? onPronunciationPlay,
}) => showModalBottomSheet<void>(
  context: context,
  isScrollControlled: true,
  useSafeArea: true,
  backgroundColor: Colors.transparent,
  barrierColor: Colors.black26,
  // The sheet draws its own handle on its own surface; the theme's would float
  // above it over the video.
  showDragHandle: false,
  constraints: BoxConstraints(
    maxHeight: MediaQuery.sizeOf(context).height * 0.62,
  ),
  builder: (sheetContext) => NightTheme(
    child: ReelTranslationBody(
      reel: reel,
      onPronunciationPlay: onPronunciationPlay,
    ),
  ),
);

class ReelTranslationBody extends ConsumerWidget {
  const ReelTranslationBody({
    required this.reel,
    this.onPronunciationPlay,
    super.key,
  });

  final Reel reel;
  final VoidCallback? onPronunciationPlay;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final brand = context.brand;
    final original = reelReadableText(reel);
    final words = reelWordMatches(original, ref.watch(dictionaryIndexProvider));
    final creatorSource = reel.isReviewed
        ? ReelContextSource.reviewed
        : ReelContextSource.creator;
    return DecoratedBox(
      decoration: BoxDecoration(
        color: brand.surfaceElevated,
        borderRadius: const BorderRadius.vertical(top: Radius.circular(24)),
        border: Border(top: BorderSide(color: brand.border)),
      ),
      child: ListView(
        shrinkWrap: true,
        padding: const EdgeInsets.fromLTRB(20, 0, 20, 28),
        children: [
          const _SheetHandle(),
          Text(
            'Translation',
            style: TextStyle(
              color: brand.ink,
              fontSize: 18,
              fontWeight: FontWeight.w800,
            ),
          ),
          if (original.trim().isNotEmpty) ...[
            const SizedBox(height: 10),
            Text(
              original.trim(),
              style: TextStyle(
                color: brand.mutedInk,
                fontSize: 14,
                height: 1.45,
                fontStyle: FontStyle.italic,
              ),
            ),
          ],
          if (reel.englishSummary.trim().isNotEmpty ||
              reel.translations.isNotEmpty)
            _Section(
              title: 'In English',
              source: creatorSource,
              children: [
                if (reel.englishSummary.trim().isNotEmpty)
                  _Body(reel.englishSummary.trim()),
                for (final meaning in reel.translations) _Bullet(meaning),
              ],
            ),
          if (words.isNotEmpty)
            _Section(
              title: 'Word by word',
              source: ReelContextSource.dictionary,
              children: [
                for (final match in words)
                  ReelWordRow(
                    match: match,
                    onPronunciationPlay: onPronunciationPlay,
                  ),
              ],
            ),
          if (words.isEmpty &&
              reel.englishSummary.trim().isEmpty &&
              reel.translations.isEmpty)
            const Padding(
              padding: EdgeInsets.only(top: 16),
              child: _Notice(
                icon: Icons.translate_rounded,
                title: 'No translation yet',
                body:
                    'Nobody has translated this piece, and none of its words '
                    'are in the dictionary yet.',
              ),
            ),
        ],
      ),
    );
  }
}

/// One dictionary word: what it is, what it means, and a way to hear it.
class ReelWordRow extends StatelessWidget {
  const ReelWordRow({
    required this.match,
    this.onPronunciationPlay,
    this.onOpened,
    super.key,
  });

  final ReelWordMatch match;
  final VoidCallback? onPronunciationPlay;
  final VoidCallback? onOpened;

  @override
  Widget build(BuildContext context) {
    final brand = context.brand;
    final entry = match.senses.first;
    final more = match.senses.length - 1;
    return Padding(
      padding: const EdgeInsets.only(bottom: 6),
      child: Row(
        children: [
          Expanded(
            child: Semantics(
              button: true,
              label:
                  '${entry.headword}: ${entry.primaryTranslation}. '
                  'Open the dictionary card',
              excludeSemantics: true,
              child: InkWell(
                borderRadius: BorderRadius.circular(10),
                onTap: () {
                  onOpened?.call();
                  showWordSenses(context, match.senses);
                },
                child: Padding(
                  padding: const EdgeInsets.symmetric(vertical: 6),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text.rich(
                        TextSpan(
                          children: [
                            TextSpan(
                              text: entry.headword,
                              style: TextStyle(
                                color: brand.ink,
                                fontSize: 15.5,
                                fontWeight: FontWeight.w800,
                              ),
                            ),
                            if (entry.pronunciation.isNotEmpty)
                              TextSpan(
                                text: '  ${entry.pronunciation}',
                                style: TextStyle(
                                  color: brand.mutedInk,
                                  fontSize: 13,
                                  fontStyle: FontStyle.italic,
                                ),
                              ),
                          ],
                        ),
                      ),
                      const SizedBox(height: 2),
                      Text(
                        more > 0
                            ? '${entry.primaryTranslation} · $more more '
                                  '${more == 1 ? 'sense' : 'senses'}'
                            : entry.primaryTranslation,
                        style: TextStyle(
                          color: brand.mutedInk,
                          fontSize: 13.5,
                          height: 1.35,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
          const SizedBox(width: 8),
          PronunciationButton(
            audioUrl: entry.audioUrl,
            onPlay: onPronunciationPlay,
          ),
        ],
      ),
    );
  }
}

// ── Kawuri's explanation ────────────────────────────────────────────────────

/// An explanation from Kawuri, asked for rather than shown by default.
///
/// ── Why it is behind a button, and labelled the way it is ──────────────────
/// A language model is confidently wrong about specific communities often
/// enough that its answer cannot sit beside a creator's own notes as though it
/// were the same kind of thing. So it is never generated until the member asks,
/// it is headed "AI-generated · not verified" in the same place every other
/// section names its source, and when the model cannot be reached the offline
/// guide's generic answer is not passed off in its place.
class ReelAiExplanation extends ConsumerStatefulWidget {
  const ReelAiExplanation({required this.reel, super.key});

  final Reel reel;

  @override
  ConsumerState<ReelAiExplanation> createState() => _ReelAiExplanationState();
}

enum _AiState { idle, loading, answered, unavailable }

class _ReelAiExplanationState extends ConsumerState<ReelAiExplanation> {
  var _state = _AiState.idle;
  var _answer = '';

  Future<void> _ask() async {
    setState(() => _state = _AiState.loading);
    final answer = await ref.read(kawuriServiceProvider).ask([
      KawuriMessage(
        id: 'explore-context-${widget.reel.id}',
        role: KawuriRole.you,
        text: reelExplanationPrompt(widget.reel),
        sentAt: DateTime.now(),
      ),
    ]);
    if (!mounted) return;
    setState(() {
      if (answer.fromOfflineGuide || answer.text.trim().isEmpty) {
        _state = _AiState.unavailable;
      } else {
        _state = _AiState.answered;
        _answer = answer.text.trim();
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    final brand = context.brand;
    switch (_state) {
      case _AiState.idle:
        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Kawuri can suggest an explanation. It may be wrong about '
              'people, places and customs, and nobody has reviewed it.',
              style: TextStyle(
                color: brand.mutedInk,
                fontSize: 13,
                height: 1.4,
              ),
            ),
            const SizedBox(height: 10),
            OutlinedButton.icon(
              onPressed: _ask,
              icon: const Icon(Icons.auto_awesome_outlined, size: 18),
              label: const Text('Ask Kawuri to explain'),
            ),
          ],
        );
      case _AiState.loading:
        return Row(
          children: [
            SizedBox.square(
              dimension: 18,
              child: CircularProgressIndicator(
                strokeWidth: 2,
                color: brand.gold,
              ),
            ),
            const SizedBox(width: 10),
            Text(
              'Kawuri is thinking…',
              style: TextStyle(color: brand.mutedInk, fontSize: 13),
            ),
          ],
        );
      case _AiState.unavailable:
        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Kawuri could not be reached, so there is no explanation to '
              'show. Nothing has been guessed in its place.',
              style: TextStyle(
                color: brand.mutedInk,
                fontSize: 13,
                height: 1.4,
              ),
            ),
            TextButton(onPressed: _ask, child: const Text('Try again')),
          ],
        );
      case _AiState.answered:
        return Container(
          width: double.infinity,
          padding: const EdgeInsets.all(12),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(14),
            border: Border.all(color: brand.gold.withValues(alpha: 0.45)),
            color: brand.gold.withValues(alpha: 0.06),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _Body(_answer),
              const SizedBox(height: 8),
              Text(
                'Generated by AI from this post’s own text. Check with the '
                'creator or the community before relying on it.',
                style: TextStyle(
                  color: brand.mutedInk,
                  fontSize: 12,
                  height: 1.35,
                  fontStyle: FontStyle.italic,
                ),
              ),
            ],
          ),
        );
    }
  }
}

/// What Kawuri is asked. Built only from what the post itself says, with the
/// instruction to say so when it is unsure rather than fill the gap.
String reelExplanationPrompt(Reel reel) {
  final lines = <String>[
    'Explain this Indigen World Explore post for a learner in 4 short '
        'sentences or fewer. Use only what is written below and general, '
        'well-established knowledge. If you are not sure about a specific '
        'community, custom or meaning, say that you are not sure instead of '
        'guessing.',
    if (reel.title.trim().isNotEmpty) 'Title: ${reel.title.trim()}',
    if (reel.caption.trim().isNotEmpty &&
        reel.caption.trim() != reel.title.trim())
      'Caption: ${reel.caption.trim()}',
    'Category: ${_sentenceCase(reel.categoryLabel)}',
    if (reel.languageLabel.isNotEmpty) 'Language: ${reel.languageLabel}',
    if (reel.dialect.trim().isNotEmpty) 'Dialect: ${reel.dialect.trim()}',
    if (reel.community != null) 'Community: ${reel.community!.name}',
    if (reel.culturalNotes.trim().isNotEmpty)
      "Creator's cultural notes: ${reel.culturalNotes.trim()}",
    if (reel.englishSummary.trim().isNotEmpty)
      "Creator's English summary: ${reel.englishSummary.trim()}",
  ];
  return lines.join('\n');
}

// ── Pieces ──────────────────────────────────────────────────────────────────

const _months = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
];

/// `13 Sep 2026`, in the reader's local time.
String formatReelDate(DateTime date) {
  final local = date.toLocal();
  return '${local.day} ${_months[local.month - 1]} ${local.year}';
}

String _sentenceCase(String shouted) {
  final lower = shouted.toLowerCase();
  return lower.isEmpty ? lower : lower[0].toUpperCase() + lower.substring(1);
}

class _SheetHandle extends StatelessWidget {
  const _SheetHandle();

  @override
  Widget build(BuildContext context) => Padding(
    padding: const EdgeInsets.symmetric(vertical: 10),
    child: Center(
      child: Container(
        width: 40,
        height: 4,
        decoration: BoxDecoration(
          color: context.brand.faintInk,
          borderRadius: BorderRadius.circular(999),
        ),
      ),
    ),
  );
}

class _Section extends StatelessWidget {
  const _Section({required this.title, required this.children, this.source});

  final String title;
  final ReelContextSource? source;
  final List<Widget> children;

  @override
  Widget build(BuildContext context) {
    final brand = context.brand;
    return Padding(
      padding: const EdgeInsets.only(top: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Divider(color: brand.divider, height: 1),
          const SizedBox(height: 14),
          Wrap(
            spacing: 8,
            runSpacing: 6,
            crossAxisAlignment: WrapCrossAlignment.center,
            children: [
              Semantics(
                header: true,
                child: Text(
                  title.toUpperCase(),
                  style: TextStyle(
                    color: brand.accent,
                    fontSize: 11,
                    fontWeight: FontWeight.w900,
                    letterSpacing: 1.1,
                  ),
                ),
              ),
              if (source != null) ReelSourceTag(source: source!),
            ],
          ),
          const SizedBox(height: 10),
          ...children,
        ],
      ),
    );
  }
}

class _Body extends StatelessWidget {
  const _Body(this.text);

  final String text;

  @override
  Widget build(BuildContext context) => Text(
    text,
    style: TextStyle(color: context.brand.ink, fontSize: 14.5, height: 1.5),
  );
}

class _Bullet extends StatelessWidget {
  const _Bullet(this.text);

  final String text;

  @override
  Widget build(BuildContext context) => Padding(
    padding: const EdgeInsets.only(bottom: 4),
    child: Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text('•  ', style: TextStyle(color: context.brand.mutedInk)),
        Expanded(child: _Body(text)),
      ],
    ),
  );
}

class _Fact extends StatelessWidget {
  const _Fact({required this.icon, required this.text});

  final IconData icon;
  final String text;

  @override
  Widget build(BuildContext context) {
    final brand = context.brand;
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 9, vertical: 5),
      decoration: BoxDecoration(
        color: brand.surfaceMuted,
        borderRadius: BorderRadius.circular(999),
        border: Border.all(color: brand.border),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 14, color: brand.mutedInk),
          const SizedBox(width: 5),
          Text(text, style: TextStyle(color: brand.ink, fontSize: 12.5)),
        ],
      ),
    );
  }
}

class _Notice extends StatelessWidget {
  const _Notice({required this.icon, required this.title, required this.body});

  final IconData icon;
  final String title;
  final String body;

  @override
  Widget build(BuildContext context) {
    final brand = context.brand;
    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: brand.surfaceMuted,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: brand.border),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(icon, size: 18, color: brand.mutedInk),
          const SizedBox(width: 10),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  title,
                  style: TextStyle(
                    color: brand.ink,
                    fontSize: 13.5,
                    fontWeight: FontWeight.w800,
                  ),
                ),
                const SizedBox(height: 3),
                Text(
                  body,
                  style: TextStyle(
                    color: brand.mutedInk,
                    fontSize: 13,
                    height: 1.4,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _RelatedLink extends StatelessWidget {
  const _RelatedLink({
    required this.icon,
    required this.label,
    required this.onTap,
  });

  final IconData icon;
  final String label;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    final brand = context.brand;
    return InkWell(
      borderRadius: BorderRadius.circular(12),
      onTap: onTap,
      child: ConstrainedBox(
        constraints: const BoxConstraints(minHeight: 48),
        child: Row(
          children: [
            Icon(icon, size: 20, color: brand.accent),
            const SizedBox(width: 12),
            Expanded(
              child: Text(
                label,
                style: TextStyle(
                  color: brand.ink,
                  fontSize: 14.5,
                  fontWeight: FontWeight.w700,
                ),
              ),
            ),
            Icon(Icons.chevron_right_rounded, color: brand.faintInk),
          ],
        ),
      ),
    );
  }
}
